### ISSUE TITLE
Why we need bable in the project, without bable can it not work.

### ISSUE THREAD

**Issue by dipti-code** [webdriverio/appium-boilerplate#70]
**Describe your question with as much detail as possible**
A clear and concise question that doesn't require too much conversation. Need more help? [Find me on Gitter](https://gitter.im/wswebcreation)

I am new, so a foolish question.
Why we need bable.?
If we needs to compiles in ES6 , is there any other tools instead of bable, why we need compiles ES2015+ down to ES5.

**If it's about a specific piece of code, try and include some of it to support your question.**
[...]

**Environment (please complete the following information):**
 - Node.js version: [e.g. 8.9.1]
 - NPM version: [e.g. 5.8.0]
 - Platform: [e.g. Android]
 - Platform version: [e.g. 8.1.0]
 - Emulator/Simulator/Real Device: [e.g. Emulator]

**Additional context**

I need to discuss in face to face. zoom would it be greate? Please send me a link.

**Comment by wswebcreation** [comment]
Hi @dipti-code 

These questions are better suited for Gitter, see also the message when you file a new ticket.

To answer your question. We sometimes need to transpile ES6 to ES5 because some JS feature, like the imports, are not supported by the nodeJS version that someone might use on his local  machine.

If you have more questions about JavaScript I would suggest you to check the internet. There are some free courses that can help you with that.
