### ISSUE TITLE
TypeError: Cannot read property 'tests' of undefined

### ISSUE THREAD

**Issue by dipti-code** [webdriverio/appium-boilerplate#75]
**Environment (please complete the following information):**
 - Node.js version: [e.g. 8.9.1]
 - NPM version: [e.g. 5.8.0]
 - Platform: [e.g. Android]
 - Platform version: [e.g. 8.1.0]
 - Emulator/Simulator/Real Device: [e.g. Emulator]

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by christian-bromann** [comment]
@dipti-code please fill out the issue template otherwise it is impossible for us to help you. We also recommend to use the Gitter channel rather than filing the issue. If you already there and no one answers to your question maybe to a bit more research on your end and reformulate your questions. Thanks!
